import type { Metadata } from "next";
import { Chewy } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";

const chewy = Chewy({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-chewy",
});

export const metadata: Metadata = {
  title: "BakeU",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${chewy.className} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
